dist: trusty
sudo: required
language: node_js
node_js:
- '8.9.4'
addons:
  chrome: stable
cache:
  apt: true
  bundler: true
  directories:
  - node_modules
script:
- ng build --prod
deploy:
  provider: firebase
  token:
    secure: 1/2bRoVlZXMDsUqWR7AzL-YDPZwP06aOQqsI6-WPTzp3q7yMgwdB5ViIbPUHtsYTFY
  skip_cleanup: true
  on:
    branch: master
